# alacritty.toml
# vim: ft=toml

#   __|    \    _ \  |      _ \   __| __ __| __ __|
#  (      _ \     /  |     (   | (_ |    |      |
# \___| _/  _\ _|_\ ____| \___/ \___|   _|     _|

# https://alacritty.org/config-alacritty.html


import  = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

live_config_reload = true

[shell]
program = "/bin/zsh"
args = []

[window]
dynamic_title = true
dimensions = { columns = 215, lines = 53 }
position = { x = 100, y = 100 }
padding = { x = 10,  y = 10 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.92
blur = true
resize_increments = true

[cursor]
style = { shape = "Block", blinking = "Off" }

[font]
normal = { family = "MonoLisa", style = "Regular" }
size = 18

[hints]
enabled = [
{ command = "open", hyperlinks = true, post_processing = true, persist = false, mouse.enabled = true, binding = { key = "U", mods = "Control|Shift" }, regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+" },
]

[keyboard]
bindings = [
{ key = "Tab", mods = "Control", chars = "\u001B[27;5;9~" },
{ key = "Tab", mods = "Control|Shift", chars = "\u001B[27;6;9~" },
]

