# alacritty.toml

#   __|    \    _ \  |      _ \   __| __ __| __ __|
#  (      _ \     /  |     (   | (_ |    |      |
# \___| _/  _\ _|_\ ____| \___/ \___|   _|     _|


import  = ["~/.config/alacritty/themes/carlogtt.toml"]

[shell]
program = "/bin/zsh"
args = []

[window]
dimensions = { columns = 215, lines = 53 }
position = { x = 100, y = 100 }
padding = { x = 10,  y = 10 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.92
blur = true
resize_increments = true

[font]
normal = { family = "MonoLisa", style = "Regular" }
size = 18

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

